// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

extension Clients {
  protocol OsConfigServiceStub: Sendable {
    func executePatchJob(
      request: ExecutePatchJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob

    func getPatchJob(
      request: GetPatchJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob

    func cancelPatchJob(
      request: CancelPatchJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob

    func listPatchJobs(
      request: ListPatchJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse

    func listPatchJobInstanceDetails(
      request: ListPatchJobInstanceDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse

    func createPatchDeployment(
      request: CreatePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    func getPatchDeployment(
      request: GetPatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    func listPatchDeployments(
      request: ListPatchDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse

    func deletePatchDeployment(
      request: DeletePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updatePatchDeployment(
      request: UpdatePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    func pausePatchDeployment(
      request: PausePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    func resumePatchDeployment(
      request: ResumePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
