// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol OsConfigZonalServiceStub: Sendable {
    func createOspolicyAssignment(
      request: CreateOSPolicyAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateOspolicyAssignment(
      request: UpdateOSPolicyAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getOspolicyAssignment(
      request: GetOSPolicyAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.OSPolicyAssignment

    func listOspolicyAssignments(
      request: ListOSPolicyAssignmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentsResponse

    func listOspolicyAssignmentRevisions(
      request: ListOSPolicyAssignmentRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentRevisionsResponse

    func deleteOspolicyAssignment(
      request: DeleteOSPolicyAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getOspolicyAssignmentReport(
      request: GetOSPolicyAssignmentReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.OSPolicyAssignmentReport

    func listOspolicyAssignmentReports(
      request: ListOSPolicyAssignmentReportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentReportsResponse

    func getInventory(
      request: GetInventoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.Inventory

    func listInventories(
      request: ListInventoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListInventoriesResponse

    func getVulnerabilityReport(
      request: GetVulnerabilityReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.VulnerabilityReport

    func listVulnerabilityReports(
      request: ListVulnerabilityReportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListVulnerabilityReportsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
