// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class OsConfigServiceTransport: OsConfigServiceStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://osconfig.googleapis.com",
      )
    }

    public func executePatchJob(
      request: ExecutePatchJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/patchJobs:execute"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchJob.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getPatchJob(
      request: GetPatchJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchJobs/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchJobs/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/patchJobs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchJob.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelPatchJob(
      request: CancelPatchJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchJobs/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):cancel"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchJobs/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/patchJobs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchJob.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listPatchJobs(
      request: ListPatchJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/patchJobs"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOSConfigV1.ListPatchJobsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listPatchJobInstanceDetails(
      request: ListPatchJobInstanceDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchJobs/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/instanceDetails"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchJobs/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/patchJobs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func createPatchDeployment(
      request: CreatePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/patchDeployments"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.patchDeploymentId, prefix: "patchDeploymentId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.patchDeployment {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchDeployment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getPatchDeployment(
      request: GetPatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/patchDeployments/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchDeployment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listPatchDeployments(
      request: ListPatchDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/patchDeployments"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudOSConfigV1.ListPatchDeploymentsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deletePatchDeployment(
      request: DeletePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/patchDeployments/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updatePatchDeployment(
      request: UpdatePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.patchDeployment.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
                .singleWildcard,
              ],
              fieldName: "patch_deployment.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.patchDeployment.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
              .singleWildcard,
            ],
            fieldName: "patch_deployment.name",
            expecting: "projects/*/patchDeployments/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.patchDeployment {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchDeployment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func pausePatchDeployment(
      request: PausePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):pause"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/patchDeployments/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchDeployment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func resumePatchDeployment(
      request: ResumePatchDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):resume"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/patchDeployments/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/patchDeployments/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudOSConfigV1.PatchDeployment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/osPolicyAssignments/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/osPolicyAssignments/"), .singleWildcard, .literal("/operations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/osPolicyAssignments/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/osPolicyAssignments/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):cancel"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/osPolicyAssignments/"), .singleWildcard, .literal("/operations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/osPolicyAssignments/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
